/* Conteúdo inicial público. Substitua pelo seed.js exportado no Studio. */
window.MG_SEED = {
  "categories": [
    "Entretenimento",
    "Vlogs",
    "Games",
    "Culinária"
  ],
  "channels": [
    {
      "id": "ch0",
      "name": "Morgílio Oficial",
      "handle": "@morgilio",
      "subs": "2,4 mi de inscritos",
      "about": "O Morgílio está em todo lugar. Uma brincadeira entre amigos.",
      "avatar": "morgilio.png",
      "banner": "morgilio.png",
      "createdAt": 1780000000000
    },
    {
      "id": "ch1",
      "name": "Morgílio Games",
      "handle": "@morgiliogames",
      "subs": "890 mil inscritos",
      "about": "O Morgílio está em todo lugar. Uma brincadeira entre amigos.",
      "avatar": "morgilio.png",
      "banner": "morgilio.png",
      "createdAt": 1780000000000
    },
    {
      "id": "ch2",
      "name": "Morgílio na Cozinha",
      "handle": "@chefemorgilio",
      "subs": "540 mil inscritos",
      "about": "O Morgílio está em todo lugar. Uma brincadeira entre amigos.",
      "avatar": "morgilio.png",
      "banner": "morgilio.png",
      "createdAt": 1780000000000
    },
    {
      "id": "ch3",
      "name": "Morgílio Vlogs",
      "handle": "@morgiliovlogs",
      "subs": "1,1 mi de inscritos",
      "about": "O Morgílio está em todo lugar. Uma brincadeira entre amigos.",
      "avatar": "morgilio.png",
      "banner": "morgilio.png",
      "createdAt": 1780000000000
    }
  ],
  "videos": [
    {
      "id": "demo1",
      "title": "Morgílio apareceu no meu recomendado de novo",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch0",
      "cat": "Entretenimento",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 120,
      "views": 15000,
      "likes": 350,
      "short": false,
      "createdAt": 1790880000000
    },
    {
      "id": "demo2",
      "title": "Tentei passar 24 horas sem falar do Morgílio",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch1",
      "cat": "Vlogs",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 163,
      "views": 72000,
      "likes": 820,
      "short": false,
      "createdAt": 1790793600000
    },
    {
      "id": "demo3",
      "title": "Morgílio zerou o jogo sem olhar para a tela",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch2",
      "cat": "Games",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 206,
      "views": 129000,
      "likes": 1290,
      "short": false,
      "createdAt": 1790707200000
    },
    {
      "id": "demo4",
      "title": "A receita secreta do Morgílio",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch3",
      "cat": "Culinária",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 249,
      "views": 186000,
      "likes": 1760,
      "short": false,
      "createdAt": 1790620800000
    },
    {
      "id": "demo5",
      "title": "Morgílio explica o inexplicável",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch0",
      "cat": "Entretenimento",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 292,
      "views": 243000,
      "likes": 2230,
      "short": false,
      "createdAt": 1790534400000
    },
    {
      "id": "demo6",
      "title": "Um dia normal na vida do Morgílio",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch1",
      "cat": "Vlogs",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 335,
      "views": 300000,
      "likes": 2700,
      "short": false,
      "createdAt": 1790448000000
    },
    {
      "id": "demo7",
      "title": "O retorno do Morgílio: agora é pessoal",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch2",
      "cat": "Games",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 378,
      "views": 357000,
      "likes": 3170,
      "short": false,
      "createdAt": 1790361600000
    },
    {
      "id": "demo8",
      "title": "Morgílio virou o dono da internet",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch3",
      "cat": "Culinária",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 421,
      "views": 414000,
      "likes": 3640,
      "short": false,
      "createdAt": 1790275200000
    },
    {
      "id": "demo9",
      "title": "O setup de milhões do Morgílio",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch0",
      "cat": "Entretenimento",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 464,
      "views": 471000,
      "likes": 4110,
      "short": false,
      "createdAt": 1790188800000
    },
    {
      "id": "demo10",
      "title": "Café com Morgílio: a entrevista que ninguém pediu",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch1",
      "cat": "Vlogs",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 507,
      "views": 528000,
      "likes": 4580,
      "short": false,
      "createdAt": 1790102400000
    },
    {
      "id": "demo11",
      "title": "Morgílio reagindo ao próprio Morgílio",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch2",
      "cat": "Games",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 550,
      "views": 585000,
      "likes": 5050,
      "short": false,
      "createdAt": 1790016000000
    },
    {
      "id": "demo12",
      "title": "Por que só aparece Morgílio no meu YouTube?",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch3",
      "cat": "Culinária",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 593,
      "views": 642000,
      "likes": 5520,
      "short": false,
      "createdAt": 1789929600000
    },
    {
      "id": "demo13",
      "title": "Morgílio em 15 segundos",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch0",
      "cat": "Entretenimento",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 15,
      "views": 699000,
      "likes": 5990,
      "short": true,
      "createdAt": 1789843200000
    },
    {
      "id": "demo14",
      "title": "POV: você encontra o Morgílio",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch1",
      "cat": "Vlogs",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 15,
      "views": 756000,
      "likes": 6460,
      "short": true,
      "createdAt": 1789756800000
    },
    {
      "id": "demo15",
      "title": "Morgílio em todos os lugares",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch2",
      "cat": "Games",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 15,
      "views": 813000,
      "likes": 6930,
      "short": true,
      "createdAt": 1789670400000
    },
    {
      "id": "demo16",
      "title": "O melhor conselho do Morgílio",
      "desc": "Uma foto, muitos títulos e um Morgílio em todo o YouTube. Conteúdo de brincadeira para entretenimento pessoal.\nEste post é uma foto: use Enviar para adicionar um vídeo real.",
      "ch": "ch3",
      "cat": "Culinária",
      "type": "image",
      "media": "morgilio.png",
      "thumb": "morgilio.png",
      "duration": 15,
      "views": 870000,
      "likes": 7400,
      "short": true,
      "createdAt": 1789584000000
    }
  ],
  "comments": []
};
